### ISSUE TITLE
issame

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [array-like/experimental#2]

**Comment by aureooms** [comment]
Alternative is
```js
import totalOrder from 'total-order';
const issame = (a,b) => totalOrder(a,b) === 0;
```

**Comment by make-github-pseudonymous-again** [comment]
Makes little sense given the flexibility needed. This is covered by `total-order` for deep comparison. For other needs one can combine `@total-order/lex` with any ternary comparator.
